package com.gmm.gctall.common.blocks;

import com.gmm.gctall.client.GctAllModels;
import com.gmm.gctall.common.blocks.BlockAbyssLiquid;
import com.gmm.gctall.common.blocks.BlockAlfCobbleStone;
import com.gmm.gctall.common.blocks.BlockAlfDirt;
import com.gmm.gctall.common.blocks.BlockAlfGrass;
import com.gmm.gctall.common.blocks.BlockAlfSand;
import com.gmm.gctall.common.blocks.BlockAlfStone;
import com.gmm.gctall.common.blocks.BlockApocalypseAltar;
import com.gmm.gctall.common.blocks.BlockApocalypseAltarBase;
import com.gmm.gctall.common.blocks.BlockApocalypseBarrier;
import com.gmm.gctall.common.blocks.BlockApocalypseBomb;
import com.gmm.gctall.common.blocks.BlockArcaneVisReceiver;
import com.gmm.gctall.common.blocks.BlockAstralPortalCore;
import com.gmm.gctall.common.blocks.BlockAzathothiumOre;
import com.gmm.gctall.common.blocks.BlockAzathothiumOreComplex;
import com.gmm.gctall.common.blocks.BlockBesideVoidPortal1;
import com.gmm.gctall.common.blocks.BlockBesideVoidPortal2;
import com.gmm.gctall.common.blocks.BlockBesideVoidPortal3;
import com.gmm.gctall.common.blocks.BlockBloodydirt;
import com.gmm.gctall.common.blocks.BlockBloodygrass;
import com.gmm.gctall.common.blocks.BlockBloodyrock;
import com.gmm.gctall.common.blocks.BlockBlueFire;
import com.gmm.gctall.common.blocks.BlockBotanicalStone;
import com.gmm.gctall.common.blocks.BlockCorruptdirt;
import com.gmm.gctall.common.blocks.BlockCorruptgrass;
import com.gmm.gctall.common.blocks.BlockCorruptrock;
import com.gmm.gctall.common.blocks.BlockCrystalsand;
import com.gmm.gctall.common.blocks.BlockCrystalsandstone;
import com.gmm.gctall.common.blocks.BlockCrystalsandstoneSlab;
import com.gmm.gctall.common.blocks.BlockCrystalsandstoneStairs;
import com.gmm.gctall.common.blocks.BlockCrystalsandstoneWalls;
import com.gmm.gctall.common.blocks.BlockDenseDarkstone;
import com.gmm.gctall.common.blocks.BlockDreadiumOre;
import com.gmm.gctall.common.blocks.BlockDreamwoodLeaves;
import com.gmm.gctall.common.blocks.BlockDreamwoodLog;
import com.gmm.gctall.common.blocks.BlockDrurceLog;
import com.gmm.gctall.common.blocks.BlockDrurcePlank;
import com.gmm.gctall.common.blocks.BlockEarthboundAltar;
import com.gmm.gctall.common.blocks.BlockEarthboundCore;
import com.gmm.gctall.common.blocks.BlockEarthboundReceiver;
import com.gmm.gctall.common.blocks.BlockElementiumOre;
import com.gmm.gctall.common.blocks.BlockEthauxiumOre;
import com.gmm.gctall.common.blocks.BlockEvileyeFence;
import com.gmm.gctall.common.blocks.BlockEvileyeLeaves;
import com.gmm.gctall.common.blocks.BlockEvileyeLog;
import com.gmm.gctall.common.blocks.BlockEvileyePlank;
import com.gmm.gctall.common.blocks.BlockEvileyeSlab;
import com.gmm.gctall.common.blocks.BlockEvileyeStair;
import com.gmm.gctall.common.blocks.BlockGravityDebris;
import com.gmm.gctall.common.blocks.BlockHeavite;
import com.gmm.gctall.common.blocks.BlockLivingwoodLeaves;
import com.gmm.gctall.common.blocks.BlockLivingwoodLog;
import com.gmm.gctall.common.blocks.BlockLunarGrass;
import com.gmm.gctall.common.blocks.BlockLunarSoil;
import com.gmm.gctall.common.blocks.BlockManaCobbleStone;
import com.gmm.gctall.common.blocks.BlockManaDirt;
import com.gmm.gctall.common.blocks.BlockManaFence;
import com.gmm.gctall.common.blocks.BlockManaGrass;
import com.gmm.gctall.common.blocks.BlockManaLeaves;
import com.gmm.gctall.common.blocks.BlockManaLog;
import com.gmm.gctall.common.blocks.BlockManaPlank;
import com.gmm.gctall.common.blocks.BlockManaSlab;
import com.gmm.gctall.common.blocks.BlockManaStairs;
import com.gmm.gctall.common.blocks.BlockManaStone;
import com.gmm.gctall.common.blocks.BlockManaStraw;
import com.gmm.gctall.common.blocks.BlockManaStrawSmall;
import com.gmm.gctall.common.blocks.BlockMeteor;
import com.gmm.gctall.common.blocks.BlockNyarlathotepiumOre;
import com.gmm.gctall.common.blocks.BlockNyralathotepiumOreComplex;
import com.gmm.gctall.common.blocks.BlockOrichalcosDreamwood;
import com.gmm.gctall.common.blocks.BlockOrichalcosOre;
import com.gmm.gctall.common.blocks.BlockPolarisite;
import com.gmm.gctall.common.blocks.BlockPolarisiteBrick;
import com.gmm.gctall.common.blocks.BlockPolarisiteDark;
import com.gmm.gctall.common.blocks.BlockPolarisiteDarkBrick;
import com.gmm.gctall.common.blocks.BlockPolarisiteDarkSlab;
import com.gmm.gctall.common.blocks.BlockPolarisiteDarkStair;
import com.gmm.gctall.common.blocks.BlockPolarisiteDarkWall;
import com.gmm.gctall.common.blocks.BlockPolarisiteSlab;
import com.gmm.gctall.common.blocks.BlockPolarisiteStair;
import com.gmm.gctall.common.blocks.BlockPolarisiteWall;
import com.gmm.gctall.common.blocks.BlockPrimordialPortalHolder;
import com.gmm.gctall.common.blocks.BlockPrimordialPortalHolder2;
import com.gmm.gctall.common.blocks.BlockPrimordialStone;
import com.gmm.gctall.common.blocks.BlockPrimordialStonebrick;
import com.gmm.gctall.common.blocks.BlockPrimordialStonebrickSlab;
import com.gmm.gctall.common.blocks.BlockPrimordialStonebrickStairs;
import com.gmm.gctall.common.blocks.BlockPrimordialStonebrickWall;
import com.gmm.gctall.common.blocks.BlockPrimordialStoneSlab;
import com.gmm.gctall.common.blocks.BlockPrimordialStoneStairs;
import com.gmm.gctall.common.blocks.BlockPrimordialStoneWall;
import com.gmm.gctall.common.blocks.BlockPrimordialVisReceiver;
import com.gmm.gctall.common.blocks.BlockReservedReserver;
import com.gmm.gctall.common.blocks.BlockReserver;
import com.gmm.gctall.common.blocks.BlockResonateDebris;
import com.gmm.gctall.common.blocks.BlockResonateDebrisCracked;
import com.gmm.gctall.common.blocks.BlockReversedAlfCobbleStone;
import com.gmm.gctall.common.blocks.BlockReversedAlfDirt;
import com.gmm.gctall.common.blocks.BlockReversedAlfGrass;
import com.gmm.gctall.common.blocks.BlockReversedAlfStone;
import com.gmm.gctall.common.blocks.BlockReversedDreamwoodFence;
import com.gmm.gctall.common.blocks.BlockReversedDreamwoodLeaves;
import com.gmm.gctall.common.blocks.BlockReversedDreamwoodLog;
import com.gmm.gctall.common.blocks.BlockReversedDreamwoodPlank;
import com.gmm.gctall.common.blocks.BlockReversedDreamwoodPlankRottened;
import com.gmm.gctall.common.blocks.BlockReversedDreamwoodSlab;
import com.gmm.gctall.common.blocks.BlockReversedDreamwoodStairs;
import com.gmm.gctall.common.blocks.BlockRuinHolder;
import com.gmm.gctall.common.blocks.BlockSaniteOre;
import com.gmm.gctall.common.blocks.BlockSanityAltar;
import com.gmm.gctall.common.blocks.BlockSeekAltar;
import com.gmm.gctall.common.blocks.BlockSeekBrick;
import com.gmm.gctall.common.blocks.BlockSeekFinder;
import com.gmm.gctall.common.blocks.BlockShubniggurathiumOre;
import com.gmm.gctall.common.blocks.BlockShubniggurathiumOreComplex;
import com.gmm.gctall.common.blocks.BlockSolidPotEnergy;
import com.gmm.gctall.common.blocks.BlockSolokFence;
import com.gmm.gctall.common.blocks.BlockSolokLeaves;
import com.gmm.gctall.common.blocks.BlockSolokLog;
import com.gmm.gctall.common.blocks.BlockSolokPlank;
import com.gmm.gctall.common.blocks.BlockSolokSlab;
import com.gmm.gctall.common.blocks.BlockSolokStair;
import com.gmm.gctall.common.blocks.BlockStarGrass;
import com.gmm.gctall.common.blocks.BlockStarSoil;
import com.gmm.gctall.common.blocks.BlockTerrasteelOre;
import com.gmm.gctall.common.blocks.BlockVoidSeedContainer;
import com.gmm.gctall.common.blocks.BlockWarprack;
import com.gmm.gctall.common.blocks.BlockWarprackSlab;
import com.gmm.gctall.common.blocks.BlockWarprackStair;
import com.gmm.gctall.common.blocks.BlockWarprackWall;
import com.gmm.gctall.common.blocks.BlockWildplainFence;
import com.gmm.gctall.common.blocks.BlockWildplainLeaves;
import com.gmm.gctall.common.blocks.BlockWildplainLog;
import com.gmm.gctall.common.blocks.BlockWildplainPlank;
import com.gmm.gctall.common.blocks.BlockWildplainSlab;
import com.gmm.gctall.common.blocks.BlockWildplainStair;
import com.gmm.gctall.common.blocks.BlockYogsothothiumOre;
import com.gmm.gctall.common.blocks.BlockYogsothothiumOreComplex;
import net.minecraft.block.Block;
import net.minecraft.block.BlockSlab;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.item.ItemSlab;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public final class GctAllBlocks {
    private GctAllBlocks() {
    }

    public static void preInit(FMLPreInitializationEvent event) {
        BlockAbyssLiquid.preInit(event);
        BlockAdeninite.preInit(event);
        BlockAetherium.preInit(event);
        BlockAwakenedDraconium.preInit(event);
        BlockBalancedMatrix.preInit(event);
        BlockBnightium.preInit(event);
        BlockCanopium.preInit(event);
        BlockChaoticDraconium.preInit(event);
        BlockDensite.preInit(event);
        BlockEverite.preInit(event);
        BlockFireAlloy.preInit(event);
        BlockFreezite.preInit(event);
        BlockGenite.preInit(event);
        BlockGuaninite.preInit(event);
        BlockIceAlloy.preInit(event);
        BlockLavarite.preInit(event);
        BlockLumixeium.preInit(event);
        BlockMistium.preInit(event);
        BlockNaturaeum.preInit(event);
        BlockNoxexeum.preInit(event);
        BlockOceanium.preInit(event);
        BlockOrderLiquid.preInit(event);
        BlockPlasmarite.preInit(event);
        BlockReditrite.preInit(event);
        BlockSkyAlloy.preInit(event);
        BlockSnowingium.preInit(event);
        BlockThyminite.preInit(event);
        BlockTonitruium.preInit(event);
    }

    public static void registerBlocks(RegistryEvent.Register<Block> event) {
        registerBlock(event, BlockAbyssLiquid.block, "abyss_liquid");
        registerBlock(event, BlockAdeninite.block, "adeninite");
        registerBlock(event, BlockAetherium.block, "aetherium");
        registerBlock(event, BlockAwakenedDraconium.block, "awakened_draconium");
        registerBlock(event, BlockBalancedMatrix.block, "balanced_matrix");
        registerBlock(event, BlockBnightium.block, "bnightium");
        registerBlock(event, BlockCanopium.block, "canopium");
        registerBlock(event, BlockChaoticDraconium.block, "chaotic_draconium");
        registerBlock(event, BlockDensite.block, "densite");
        registerBlock(event, BlockEverite.block, "everite");
        registerBlock(event, BlockFireAlloy.block, "fire_alloy");
        registerBlock(event, BlockFreezite.block, "freezite");
        registerBlock(event, BlockGenite.block, "genite");
        registerBlock(event, BlockGuaninite.block, "guaninite");
        registerBlock(event, BlockIceAlloy.block, "ice_alloy");
        registerBlock(event, BlockLavarite.block, "lavarite");
        registerBlock(event, BlockLumixeium.block, "lumixeium");
        registerBlock(event, BlockMistium.block, "mistium");
        registerBlock(event, BlockNaturaeum.block, "naturaeum");
        registerBlock(event, BlockNoxexeum.block, "noxexeum");
        registerBlock(event, BlockOceanium.block, "oceanium");
        registerBlock(event, BlockOrderLiquid.block, "order_liquid");
        registerBlock(event, BlockOrderCrystalOre.block, "order_crystal_ore");
        registerBlock(event, BlockFinalliumContainer.block, "finallium_container");
        registerBlock(event, BlockFinalliumContainerActive.block, "finallium_container_active");
        registerBlock(event, BlockPlasmarite.block, "plasmarite");
        registerBlock(event, BlockReditrite.block, "reditrite");
        registerBlock(event, BlockSkyAlloy.block, "sky_alloy");
        registerBlock(event, BlockSnowingium.block, "snowingium");
        registerBlock(event, BlockThyminite.block, "thyminite");
        registerBlock(event, BlockTonitruium.block, "tonitruium");
        registerBlock(event, BlockWitheriumOreEnd.block, "witherium_ore_end");
        registerBlock(event, BlockWitheriumOreNether.block, "witherium_ore_nether");
        registerBlock(event, BlockWitheriumOreOverworld.block, "witherium_ore_overworld");
        registerBlock(event, BlockAlfCobbleStone.block, "alf_cobble_stone");
        registerBlock(event, BlockAlfDirt.block, "alf_dirt");
        registerBlock(event, BlockAlfGrass.block, "alf_grass");
        registerBlock(event, BlockAlfSand.block, "alf_sand");
        registerBlock(event, BlockAlfStone.block, "alf_stone");
        registerBlock(event, BlockApocalypseAltar.block, "apocalypse_altar");
        registerBlock(event, BlockApocalypseAltarBase.block, "apocalypse_altar_base");
        registerBlock(event, BlockApocalypseBarrier.block, "apocalypse_barrier");
        registerBlock(event, BlockApocalypseBomb.block, "apocalypse_bomb");
        registerBlock(event, BlockArcaneVisReceiver.block, "arcane_vis_receiver");
        registerBlock(event, BlockAstralPortalCore.block, "astral_portal_core");
        registerBlock(event, BlockAzathothiumOre.block, "azathothium_ore");
        registerBlock(event, BlockAzathothiumOreComplex.block, "azathothium_ore_complex");
        registerBlock(event, BlockBesideVoidPortal1.block, "beside_void_portal_1");
        registerBlock(event, BlockBesideVoidPortal2.block, "beside_void_portal_2");
        registerBlock(event, BlockBesideVoidPortal3.block, "beside_void_portal_3");
        registerBlock(event, BlockBloodydirt.block, "bloodydirt");
        registerBlock(event, BlockBloodygrass.block, "bloodygrass");
        registerBlock(event, BlockBloodyrock.block, "bloodyrock");
        registerBlock(event, BlockBlueFire.block, "blue_fire");
        registerBlock(event, BlockBotanicalStone.block, "botanical_stone");
        registerBlock(event, BlockCorruptdirt.block, "corruptdirt");
        registerBlock(event, BlockCorruptgrass.block, "corruptgrass");
        registerBlock(event, BlockCorruptrock.block, "corruptrock");
        registerBlock(event, BlockCrystalsand.block, "crystalsand");
        registerBlock(event, BlockCrystalsandstone.block, "crystalsandstone");
        registerBlock(event, BlockCrystalsandstoneSlab.block, "crystalsandstone_slab");
        registerBlock(event, BlockCrystalsandstoneSlab.block_slab_double, "crystalsandstone_slab_double");
        registerBlock(event, BlockCrystalsandstoneStairs.block, "crystalsandstone_stairs");
        registerBlock(event, BlockCrystalsandstoneWalls.block, "crystalsandstone_walls");
        registerBlock(event, BlockDenseDarkstone.block, "densedarkstone");
        registerBlock(event, BlockDreadiumOre.block, "dreadiumore");
        registerBlock(event, BlockDreamwoodLeaves.block, "dreamwood_leaves");
        registerBlock(event, BlockDreamwoodLog.block, "dreamwood_log");
        registerBlock(event, BlockDrurceLog.block, "drurce_log");
        registerBlock(event, BlockDrurcePlank.block, "drurce_plank");
        registerBlock(event, BlockEarthboundAltar.block, "earthbound_altar");
        registerBlock(event, BlockEarthboundCore.block, "earthbound_core");
        registerBlock(event, BlockEarthboundReceiver.block, "earthbound_receiver");
        registerBlock(event, BlockElementiumOre.block, "elementium_ore");
        registerBlock(event, BlockEthauxiumOre.block, "ethauxiumore");
        registerBlock(event, BlockEvileyeFence.block, "evileye_fence");
        registerBlock(event, BlockEvileyeLeaves.block, "evileye_leaves");
        registerBlock(event, BlockEvileyeLog.block, "evileye_log");
        registerBlock(event, BlockEvileyePlank.block, "evileye_plank");
        registerBlock(event, BlockEvileyeSlab.block, "evileye_slab");
        registerBlock(event, BlockEvileyeSlab.block_slab_double, "evileye_slab_double");
        registerBlock(event, BlockEvileyeStair.block, "evileye_stair");
        registerBlock(event, BlockGravityDebris.block, "gravity_debris");
        registerBlock(event, BlockHeavite.block, "heavite");
        registerBlock(event, BlockLivingwoodLeaves.block, "livingwood_leaves");
        registerBlock(event, BlockLivingwoodLog.block, "livingwood_log");
        registerBlock(event, BlockLunarGrass.block, "lunar_grass");
        registerBlock(event, BlockLunarSoil.block, "lunar_soil");
        registerBlock(event, BlockManaCobbleStone.block, "mana_cobble_stone");
        registerBlock(event, BlockManaDirt.block, "mana_dirt");
        registerBlock(event, BlockManaFence.block, "mana_fence");
        registerBlock(event, BlockManaGrass.block, "mana_grass");
        registerBlock(event, BlockManaLeaves.block, "mana_leaves");
        registerBlock(event, BlockManaLog.block, "mana_log");
        registerBlock(event, BlockManaPlank.block, "mana_plank");
        registerBlock(event, BlockManaSlab.block, "mana_slab");
        registerBlock(event, BlockManaSlab.block_slab_double, "mana_slab_double");
        registerBlock(event, BlockManaStairs.block, "mana_stairs");
        registerBlock(event, BlockManaStone.block, "mana_stone");
        registerBlock(event, BlockManaStraw.block, "mana_straw");
        registerBlock(event, BlockManaStrawSmall.block, "mana_straw_small");
        registerBlock(event, BlockMeteor.block, "meteor");
        registerBlock(event, BlockNyarlathotepiumOre.block, "nyarlathotepium_ore");
        registerBlock(event, BlockNyralathotepiumOreComplex.block, "nyralathotepium_ore_complex");
        registerBlock(event, BlockOrichalcosDreamwood.block, "orichalcos_dreamwood");
        registerBlock(event, BlockOrichalcosOre.block, "orichalcos_ore");
        registerBlock(event, BlockPolarisite.block, "polarisite");
        registerBlock(event, BlockPolarisiteBrick.block, "polarisite_brick");
        registerBlock(event, BlockPolarisiteDark.block, "polarisite_dark");
        registerBlock(event, BlockPolarisiteDarkBrick.block, "polarisite_dark_brick");
        registerBlock(event, BlockPolarisiteDarkSlab.block, "polarisite_dark_slab");
        registerBlock(event, BlockPolarisiteDarkSlab.block_slab_double, "polarisite_dark_slab_double");
        registerBlock(event, BlockPolarisiteDarkStair.block, "polarisite_dark_stair");
        registerBlock(event, BlockPolarisiteDarkWall.block, "polarisite_dark_wall");
        registerBlock(event, BlockPolarisiteSlab.block, "polarisite_slab");
        registerBlock(event, BlockPolarisiteSlab.block_slab_double, "polarisite_slab_double");
        registerBlock(event, BlockPolarisiteStair.block, "polarisite_stair");
        registerBlock(event, BlockPolarisiteWall.block, "polarisite_wall");
        registerBlock(event, BlockPrimordialPortalHolder.block, "primordial_portal_holder_up");
        registerBlock(event, BlockPrimordialPortalHolder2.block, "primordial_portal_holder_down");
        registerBlock(event, BlockPrimordialStone.block, "primordial_stone");
        registerBlock(event, BlockPrimordialStonebrick.block, "primordial_stonebrick");
        registerBlock(event, BlockPrimordialStonebrickSlab.block, "primordial_stonebrick_slab");
        registerBlock(event, BlockPrimordialStonebrickSlab.block_slab_double, "primordial_stonebrick_slab_double");
        registerBlock(event, BlockPrimordialStonebrickStairs.block, "primordial_stonebrick_stairs");
        registerBlock(event, BlockPrimordialStonebrickWall.block, "primordial_stonebrick_wall");
        registerBlock(event, BlockPrimordialStoneSlab.block, "primordial_stone_slab");
        registerBlock(event, BlockPrimordialStoneSlab.block_slab_double, "primordial_stone_slab_double");
        registerBlock(event, BlockPrimordialStoneStairs.block, "primordial_stone_stairs");
        registerBlock(event, BlockPrimordialStoneWall.block, "primordial_stone_wall");
        registerBlock(event, BlockPrimordialVisReceiver.block, "primordial_vis_receiver");
        registerBlock(event, BlockReservedReserver.block, "reserved_reserver");
        registerBlock(event, BlockReserver.block, "reserver");
        registerBlock(event, BlockResonateDebris.block, "resonate_debris");
        registerBlock(event, BlockResonateDebrisCracked.block, "resonate_debris_cracked");
        registerBlock(event, BlockReversedAlfCobbleStone.block, "reversed_alf_cobble_stone");
        registerBlock(event, BlockReversedAlfDirt.block, "reversed_alf_dirt");
        registerBlock(event, BlockReversedAlfGrass.block, "reversed_alf_grass");
        registerBlock(event, BlockReversedAlfStone.block, "reversed_alf_stone");
        registerBlock(event, BlockReversedDreamwoodFence.block, "reversed_dreamwood_fence");
        registerBlock(event, BlockReversedDreamwoodLeaves.block, "reversed_dreamwood_leaves");
        registerBlock(event, BlockReversedDreamwoodLog.block, "reversed_dreamwood_log");
        registerBlock(event, BlockReversedDreamwoodPlank.block, "reversed_dreamwood_plank");
        registerBlock(event, BlockReversedDreamwoodPlankRottened.block, "reversed_dreamwood_plank_rottened");
        registerBlock(event, BlockReversedDreamwoodSlab.block, "reversed_dreamwood_slab");
        registerBlock(event, BlockReversedDreamwoodSlab.block_slab_double, "reversed_dreamwood_slab_double");
        registerBlock(event, BlockReversedDreamwoodStairs.block, "reversed_dreamwood_stairs");
        registerBlock(event, BlockRuinHolder.block, "ruin_holder");
        registerBlock(event, BlockSaniteOre.block, "saniteore");
        registerBlock(event, BlockSanityAltar.block, "sanity_altar");
        registerBlock(event, BlockSeekAltar.block, "seek_altar");
        registerBlock(event, BlockSeekBrick.block, "seek_brick");
        registerBlock(event, BlockSeekFinder.block, "seek_finder");
        registerBlock(event, BlockShubniggurathiumOre.block, "shubniggurathium_ore");
        registerBlock(event, BlockShubniggurathiumOreComplex.block, "shubniggurathium_ore_complex");
        registerBlock(event, BlockSolidPotEnergy.block, "solid_pot_energy");
        registerBlock(event, BlockSolokFence.block, "solok_fence");
        registerBlock(event, BlockSolokLeaves.block, "solok_leaves");
        registerBlock(event, BlockSolokLog.block, "solok_log");
        registerBlock(event, BlockSolokPlank.block, "solok_plank");
        registerBlock(event, BlockSolokSlab.block, "solok_slab");
        registerBlock(event, BlockSolokSlab.block_slab_double, "solok_slab_double");
        registerBlock(event, BlockSolokStair.block, "solok_stair");
        registerBlock(event, BlockStarGrass.block, "star_grass");
        registerBlock(event, BlockStarSoil.block, "star_soil");
        registerBlock(event, BlockTerrasteelOre.block, "terrasteel_ore");
        registerBlock(event, BlockVoidSeedContainer.block, "void_seed_container");
        registerBlock(event, BlockWarprack.block, "warprack");
        registerBlock(event, BlockWarprackSlab.block, "warprack_slab");
        registerBlock(event, BlockWarprackSlab.block_slab_double, "warprack_slab_double");
        registerBlock(event, BlockWarprackStair.block, "warprack_stair");
        registerBlock(event, BlockWarprackWall.block, "warprack_wall");
        registerBlock(event, BlockWildplainFence.block, "wildplain_fence");
        registerBlock(event, BlockWildplainLeaves.block, "wildplain_leaves");
        registerBlock(event, BlockWildplainLog.block, "wildplain_log");
        registerBlock(event, BlockWildplainPlank.block, "wildplain_plank");
        registerBlock(event, BlockWildplainSlab.block, "wildplain_slab");
        registerBlock(event, BlockWildplainSlab.block_slab_double, "wildplain_slab_double");
        registerBlock(event, BlockWildplainStair.block, "wildplain_stair");
        registerBlock(event, BlockYogsothothiumOre.block, "yogsothothium_ore");
        registerBlock(event, BlockYogsothothiumOreComplex.block, "yogsothothium_ore_complex");
        registerBlock(event, BlockDawniumOre.block, "dawnium_ore");
        registerBlock(event, BlockDeepslate.block, "deepslate");
        registerBlock(event, BlockGlowstoneStair.block, "glowstone_stair");
        registerBlock(event, BlockOrderCobblestone.block, "order_cobblestone");
        registerBlock(event, BlockOrderCrystalBlock.block, "order_crystal_block");
        registerBlock(event, BlockOrderStone.block, "order_stone");
        registerBlock(event, BlockOrderStoneBase.block, "order_stone_base");
        registerBlock(event, BlockOrderStoneBrick.block, "order_stone_brick");
        registerBlock(event, BlockOrderStoneBrickChiseled.block, "order_stone_brick_chiseled");
        registerBlock(event, BlockOrderStoneBrickCrashed.block, "order_stone_brick_crashed");
        registerBlock(event, BlockOrderStoneBrickCrashedSlab.block, "order_stone_brick_crashed_slab");
        registerBlock(event, BlockOrderStoneBrickCrashedSlab.block_slab_double, "order_stone_brick_crashed_slab_double");
        registerBlock(event, BlockOrderStoneBrickCrashedStair.block, "order_stone_brick_crashed_stair");
        registerBlock(event, BlockOrderStoneBrickCrashedWall.block, "order_stone_brick_crashed_wall");
        registerBlock(event, BlockOrderStoneBrickSlab.block, "order_stone_brick_slab");
        registerBlock(event, BlockOrderStoneBrickSlab.block_slab_double, "order_stone_brick_slab_double");
        registerBlock(event, BlockOrderStoneBrickStair.block, "order_stone_brick_stair");
        registerBlock(event, BlockOrderStoneBrickWall.block, "order_stone_brick_wall");
        registerBlock(event, BlockOrderStoneFinal.block, "order_stone_final");
        registerBlock(event, BlockRainboquartzBlock.block, "rainboquartz_block");
        registerBlock(event, BlockRainboquartzBlockChiseled.block, "rainboquartz_block_chiseled");
        registerBlock(event, BlockRainboquartzSlab.block, "rainboquartz_slab");
        registerBlock(event, BlockRainboquartzSlab.block_slab_double, "rainboquartz_slab_double");
        registerBlock(event, BlockRainboquartzStair.block, "rainboquartz_stair");
        registerBlock(event, BlockReditriteCobblestone.block, "reditrite_cobblestone");
        registerBlock(event, BlockSenterianBuilderLab.block, "senterian_builder_lab");
        registerBlock(event, BlockSenterianCase1.block, "senterian_case_1");
        registerBlock(event, BlockSenterianCase2.block, "senterian_case_2");
        registerBlock(event, BlockSenterianCase3.block, "senterian_case_3");
        registerBlock(event, BlockSenterianCase4.block, "senterian_case_4");
        registerBlock(event, BlockSenterianCase5.block, "senterian_case_5");
        registerBlock(event, BlockSenterianCase6.block, "senterian_case_6");
        registerBlock(event, BlockSenterianCase7.block, "senterian_case_7");
        registerBlock(event, BlockSenterianCase8.block, "senterian_case_8");
        registerBlock(event, BlockSenterianLament.block, "senterian_lament");
        registerBlock(event, BlockSenterianLock.block, "senterian_lock");
        registerBlock(event, BlockSenterianSummonerSmall.block, "senterian_summoner_small");
        registerBlock(event, BlockSenterianSummoner.block, "senterian_summoner");
        registerBlock(event, BlockShalloiteBlock.block, "shalloite_block");
        registerBlock(event, BlockShalloiteBlockChiseled.block, "shalloite_block_chiseled");
        registerBlock(event, BlockShalloiteSlab.block, "shalloite_slab");
        registerBlock(event, BlockShalloiteSlab.block_slab_double, "shalloite_slab_double");
        registerBlock(event, BlockShalloiteStair.block, "shalloite_stair");
    }

    public static void registerItems(RegistryEvent.Register<Item> event) {
        event.getRegistry().register(BlockAbyssLiquid.item.setRegistryName(BlockAbyssLiquid.block.getRegistryName()));
        event.getRegistry().register(BlockAdeninite.item.setRegistryName(BlockAdeninite.block.getRegistryName()));
        event.getRegistry().register(BlockAetherium.item.setRegistryName(BlockAetherium.block.getRegistryName()));
        event.getRegistry().register(BlockAwakenedDraconium.item.setRegistryName(BlockAwakenedDraconium.block.getRegistryName()));
        event.getRegistry().register(BlockBalancedMatrix.item.setRegistryName(BlockBalancedMatrix.block.getRegistryName()));
        event.getRegistry().register(BlockBnightium.item.setRegistryName(BlockBnightium.block.getRegistryName()));
        event.getRegistry().register(BlockCanopium.item.setRegistryName(BlockCanopium.block.getRegistryName()));
        event.getRegistry().register(BlockChaoticDraconium.item.setRegistryName(BlockChaoticDraconium.block.getRegistryName()));
        event.getRegistry().register(BlockDensite.item.setRegistryName(BlockDensite.block.getRegistryName()));
        event.getRegistry().register(BlockEverite.item.setRegistryName(BlockEverite.block.getRegistryName()));
        event.getRegistry().register(BlockFireAlloy.item.setRegistryName(BlockFireAlloy.block.getRegistryName()));
        event.getRegistry().register(BlockFreezite.item.setRegistryName(BlockFreezite.block.getRegistryName()));
        event.getRegistry().register(BlockGenite.item.setRegistryName(BlockGenite.block.getRegistryName()));
        event.getRegistry().register(BlockGuaninite.item.setRegistryName(BlockGuaninite.block.getRegistryName()));
        event.getRegistry().register(BlockIceAlloy.item.setRegistryName(BlockIceAlloy.block.getRegistryName()));
        event.getRegistry().register(BlockLavarite.item.setRegistryName(BlockLavarite.block.getRegistryName()));
        event.getRegistry().register(BlockLumixeium.item.setRegistryName(BlockLumixeium.block.getRegistryName()));
        event.getRegistry().register(BlockMistium.item.setRegistryName(BlockMistium.block.getRegistryName()));
        event.getRegistry().register(BlockNaturaeum.item.setRegistryName(BlockNaturaeum.block.getRegistryName()));
        event.getRegistry().register(BlockNoxexeum.item.setRegistryName(BlockNoxexeum.block.getRegistryName()));
        event.getRegistry().register(BlockOceanium.item.setRegistryName(BlockOceanium.block.getRegistryName()));
        event.getRegistry().register(BlockOrderLiquid.item.setRegistryName(BlockOrderLiquid.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderCrystalOre.block).setRegistryName(BlockOrderCrystalOre.block.getRegistryName()));
        event.getRegistry().register(BlockFinalliumContainer.item.setRegistryName(BlockFinalliumContainer.block.getRegistryName()));
        event.getRegistry().register(BlockFinalliumContainerActive.item.setRegistryName(BlockFinalliumContainerActive.block.getRegistryName()));
        event.getRegistry().register(BlockPlasmarite.item.setRegistryName(BlockPlasmarite.block.getRegistryName()));
        event.getRegistry().register(BlockReditrite.item.setRegistryName(BlockReditrite.block.getRegistryName()));
        event.getRegistry().register(BlockSkyAlloy.item.setRegistryName(BlockSkyAlloy.block.getRegistryName()));
        event.getRegistry().register(BlockSnowingium.item.setRegistryName(BlockSnowingium.block.getRegistryName()));
        event.getRegistry().register(BlockThyminite.item.setRegistryName(BlockThyminite.block.getRegistryName()));
        event.getRegistry().register(BlockTonitruium.item.setRegistryName(BlockTonitruium.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWitheriumOreEnd.block).setRegistryName(BlockWitheriumOreEnd.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWitheriumOreNether.block).setRegistryName(BlockWitheriumOreNether.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWitheriumOreOverworld.block).setRegistryName(BlockWitheriumOreOverworld.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAlfCobbleStone.block).setRegistryName(BlockAlfCobbleStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAlfDirt.block).setRegistryName(BlockAlfDirt.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAlfGrass.block).setRegistryName(BlockAlfGrass.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAlfSand.block).setRegistryName(BlockAlfSand.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAlfStone.block).setRegistryName(BlockAlfStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockApocalypseAltar.block).setRegistryName(BlockApocalypseAltar.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockApocalypseAltarBase.block).setRegistryName(BlockApocalypseAltarBase.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockApocalypseBarrier.block).setRegistryName(BlockApocalypseBarrier.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockApocalypseBomb.block).setRegistryName(BlockApocalypseBomb.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockArcaneVisReceiver.block).setRegistryName(BlockArcaneVisReceiver.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAstralPortalCore.block).setRegistryName(BlockAstralPortalCore.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAzathothiumOre.block).setRegistryName(BlockAzathothiumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockAzathothiumOreComplex.block).setRegistryName(BlockAzathothiumOreComplex.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBesideVoidPortal1.block).setRegistryName(BlockBesideVoidPortal1.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBesideVoidPortal2.block).setRegistryName(BlockBesideVoidPortal2.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBesideVoidPortal3.block).setRegistryName(BlockBesideVoidPortal3.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBloodydirt.block).setRegistryName(BlockBloodydirt.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBloodygrass.block).setRegistryName(BlockBloodygrass.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBloodyrock.block).setRegistryName(BlockBloodyrock.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBlueFire.block).setRegistryName(BlockBlueFire.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockBotanicalStone.block).setRegistryName(BlockBotanicalStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockCorruptdirt.block).setRegistryName(BlockCorruptdirt.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockCorruptgrass.block).setRegistryName(BlockCorruptgrass.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockCorruptrock.block).setRegistryName(BlockCorruptrock.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockCrystalsand.block).setRegistryName(BlockCrystalsand.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockCrystalsandstone.block).setRegistryName(BlockCrystalsandstone.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockCrystalsandstoneSlab.block, (BlockSlab) BlockCrystalsandstoneSlab.block, (BlockSlab) BlockCrystalsandstoneSlab.block_slab_double).setRegistryName(BlockCrystalsandstoneSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockCrystalsandstoneStairs.block).setRegistryName(BlockCrystalsandstoneStairs.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockCrystalsandstoneWalls.block).setRegistryName(BlockCrystalsandstoneWalls.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDenseDarkstone.block).setRegistryName(BlockDenseDarkstone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDreadiumOre.block).setRegistryName(BlockDreadiumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDreamwoodLeaves.block).setRegistryName(BlockDreamwoodLeaves.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDreamwoodLog.block).setRegistryName(BlockDreamwoodLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDrurceLog.block).setRegistryName(BlockDrurceLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDrurcePlank.block).setRegistryName(BlockDrurcePlank.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEarthboundAltar.block).setRegistryName(BlockEarthboundAltar.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEarthboundCore.block).setRegistryName(BlockEarthboundCore.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEarthboundReceiver.block).setRegistryName(BlockEarthboundReceiver.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockElementiumOre.block).setRegistryName(BlockElementiumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEthauxiumOre.block).setRegistryName(BlockEthauxiumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEvileyeFence.block).setRegistryName(BlockEvileyeFence.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEvileyeLeaves.block).setRegistryName(BlockEvileyeLeaves.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEvileyeLog.block).setRegistryName(BlockEvileyeLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEvileyePlank.block).setRegistryName(BlockEvileyePlank.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockEvileyeSlab.block, (BlockSlab) BlockEvileyeSlab.block, (BlockSlab) BlockEvileyeSlab.block_slab_double).setRegistryName(BlockEvileyeSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockEvileyeStair.block).setRegistryName(BlockEvileyeStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockGravityDebris.block).setRegistryName(BlockGravityDebris.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockHeavite.block).setRegistryName(BlockHeavite.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockLivingwoodLeaves.block).setRegistryName(BlockLivingwoodLeaves.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockLivingwoodLog.block).setRegistryName(BlockLivingwoodLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockLunarGrass.block).setRegistryName(BlockLunarGrass.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockLunarSoil.block).setRegistryName(BlockLunarSoil.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaCobbleStone.block).setRegistryName(BlockManaCobbleStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaDirt.block).setRegistryName(BlockManaDirt.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaFence.block).setRegistryName(BlockManaFence.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaGrass.block).setRegistryName(BlockManaGrass.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaLeaves.block).setRegistryName(BlockManaLeaves.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaLog.block).setRegistryName(BlockManaLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaPlank.block).setRegistryName(BlockManaPlank.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockManaSlab.block, (BlockSlab) BlockManaSlab.block, (BlockSlab) BlockManaSlab.block_slab_double).setRegistryName(BlockManaSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaStairs.block).setRegistryName(BlockManaStairs.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaStone.block).setRegistryName(BlockManaStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaStraw.block).setRegistryName(BlockManaStraw.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockManaStrawSmall.block).setRegistryName(BlockManaStrawSmall.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockMeteor.block).setRegistryName(BlockMeteor.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockNyarlathotepiumOre.block).setRegistryName(BlockNyarlathotepiumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockNyralathotepiumOreComplex.block).setRegistryName(BlockNyralathotepiumOreComplex.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrichalcosDreamwood.block).setRegistryName(BlockOrichalcosDreamwood.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrichalcosOre.block).setRegistryName(BlockOrichalcosOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisite.block).setRegistryName(BlockPolarisite.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisiteBrick.block).setRegistryName(BlockPolarisiteBrick.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisiteDark.block).setRegistryName(BlockPolarisiteDark.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisiteDarkBrick.block).setRegistryName(BlockPolarisiteDarkBrick.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockPolarisiteDarkSlab.block, (BlockSlab) BlockPolarisiteDarkSlab.block, (BlockSlab) BlockPolarisiteDarkSlab.block_slab_double).setRegistryName(BlockPolarisiteDarkSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisiteDarkStair.block).setRegistryName(BlockPolarisiteDarkStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisiteDarkWall.block).setRegistryName(BlockPolarisiteDarkWall.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockPolarisiteSlab.block, (BlockSlab) BlockPolarisiteSlab.block, (BlockSlab) BlockPolarisiteSlab.block_slab_double).setRegistryName(BlockPolarisiteSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisiteStair.block).setRegistryName(BlockPolarisiteStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPolarisiteWall.block).setRegistryName(BlockPolarisiteWall.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialPortalHolder.block).setRegistryName(BlockPrimordialPortalHolder.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialPortalHolder2.block).setRegistryName(BlockPrimordialPortalHolder2.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialStone.block).setRegistryName(BlockPrimordialStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialStonebrick.block).setRegistryName(BlockPrimordialStonebrick.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockPrimordialStonebrickSlab.block, (BlockSlab) BlockPrimordialStonebrickSlab.block, (BlockSlab) BlockPrimordialStonebrickSlab.block_slab_double).setRegistryName(BlockPrimordialStonebrickSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialStonebrickStairs.block).setRegistryName(BlockPrimordialStonebrickStairs.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialStonebrickWall.block).setRegistryName(BlockPrimordialStonebrickWall.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockPrimordialStoneSlab.block, (BlockSlab) BlockPrimordialStoneSlab.block, (BlockSlab) BlockPrimordialStoneSlab.block_slab_double).setRegistryName(BlockPrimordialStoneSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialStoneStairs.block).setRegistryName(BlockPrimordialStoneStairs.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialStoneWall.block).setRegistryName(BlockPrimordialStoneWall.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockPrimordialVisReceiver.block).setRegistryName(BlockPrimordialVisReceiver.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReservedReserver.block).setRegistryName(BlockReservedReserver.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReserver.block).setRegistryName(BlockReserver.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockResonateDebris.block).setRegistryName(BlockResonateDebris.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockResonateDebrisCracked.block).setRegistryName(BlockResonateDebrisCracked.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedAlfCobbleStone.block).setRegistryName(BlockReversedAlfCobbleStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedAlfDirt.block).setRegistryName(BlockReversedAlfDirt.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedAlfGrass.block).setRegistryName(BlockReversedAlfGrass.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedAlfStone.block).setRegistryName(BlockReversedAlfStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedDreamwoodFence.block).setRegistryName(BlockReversedDreamwoodFence.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedDreamwoodLeaves.block).setRegistryName(BlockReversedDreamwoodLeaves.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedDreamwoodLog.block).setRegistryName(BlockReversedDreamwoodLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedDreamwoodPlank.block).setRegistryName(BlockReversedDreamwoodPlank.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedDreamwoodPlankRottened.block).setRegistryName(BlockReversedDreamwoodPlankRottened.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockReversedDreamwoodSlab.block, (BlockSlab) BlockReversedDreamwoodSlab.block, (BlockSlab) BlockReversedDreamwoodSlab.block_slab_double).setRegistryName(BlockReversedDreamwoodSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReversedDreamwoodStairs.block).setRegistryName(BlockReversedDreamwoodStairs.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockRuinHolder.block).setRegistryName(BlockRuinHolder.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSaniteOre.block).setRegistryName(BlockSaniteOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSanityAltar.block).setRegistryName(BlockSanityAltar.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSeekAltar.block).setRegistryName(BlockSeekAltar.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSeekBrick.block).setRegistryName(BlockSeekBrick.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSeekFinder.block).setRegistryName(BlockSeekFinder.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockShubniggurathiumOre.block).setRegistryName(BlockShubniggurathiumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockShubniggurathiumOreComplex.block).setRegistryName(BlockShubniggurathiumOreComplex.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSolidPotEnergy.block).setRegistryName(BlockSolidPotEnergy.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSolokFence.block).setRegistryName(BlockSolokFence.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSolokLeaves.block).setRegistryName(BlockSolokLeaves.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSolokLog.block).setRegistryName(BlockSolokLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSolokPlank.block).setRegistryName(BlockSolokPlank.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockSolokSlab.block, (BlockSlab) BlockSolokSlab.block, (BlockSlab) BlockSolokSlab.block_slab_double).setRegistryName(BlockSolokSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSolokStair.block).setRegistryName(BlockSolokStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockStarGrass.block).setRegistryName(BlockStarGrass.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockStarSoil.block).setRegistryName(BlockStarSoil.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockTerrasteelOre.block).setRegistryName(BlockTerrasteelOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockVoidSeedContainer.block).setRegistryName(BlockVoidSeedContainer.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWarprack.block).setRegistryName(BlockWarprack.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockWarprackSlab.block, (BlockSlab) BlockWarprackSlab.block, (BlockSlab) BlockWarprackSlab.block_slab_double).setRegistryName(BlockWarprackSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWarprackStair.block).setRegistryName(BlockWarprackStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWarprackWall.block).setRegistryName(BlockWarprackWall.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWildplainFence.block).setRegistryName(BlockWildplainFence.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWildplainLeaves.block).setRegistryName(BlockWildplainLeaves.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWildplainLog.block).setRegistryName(BlockWildplainLog.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWildplainPlank.block).setRegistryName(BlockWildplainPlank.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockWildplainSlab.block, (BlockSlab) BlockWildplainSlab.block, (BlockSlab) BlockWildplainSlab.block_slab_double).setRegistryName(BlockWildplainSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockWildplainStair.block).setRegistryName(BlockWildplainStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockYogsothothiumOre.block).setRegistryName(BlockYogsothothiumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockYogsothothiumOreComplex.block).setRegistryName(BlockYogsothothiumOreComplex.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDawniumOre.block).setRegistryName(BlockDawniumOre.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockDeepslate.block).setRegistryName(BlockDeepslate.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockGlowstoneStair.block).setRegistryName(BlockGlowstoneStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderCobblestone.block).setRegistryName(BlockOrderCobblestone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderCrystalBlock.block).setRegistryName(BlockOrderCrystalBlock.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStone.block).setRegistryName(BlockOrderStone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBase.block).setRegistryName(BlockOrderStoneBase.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBrick.block).setRegistryName(BlockOrderStoneBrick.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBrickChiseled.block).setRegistryName(BlockOrderStoneBrickChiseled.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBrickCrashed.block).setRegistryName(BlockOrderStoneBrickCrashed.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockOrderStoneBrickCrashedSlab.block, (BlockSlab) BlockOrderStoneBrickCrashedSlab.block, (BlockSlab) BlockOrderStoneBrickCrashedSlab.block_slab_double).setRegistryName(BlockOrderStoneBrickCrashedSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBrickCrashedStair.block).setRegistryName(BlockOrderStoneBrickCrashedStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBrickCrashedWall.block).setRegistryName(BlockOrderStoneBrickCrashedWall.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockOrderStoneBrickSlab.block, (BlockSlab) BlockOrderStoneBrickSlab.block, (BlockSlab) BlockOrderStoneBrickSlab.block_slab_double).setRegistryName(BlockOrderStoneBrickSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBrickStair.block).setRegistryName(BlockOrderStoneBrickStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneBrickWall.block).setRegistryName(BlockOrderStoneBrickWall.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockOrderStoneFinal.block).setRegistryName(BlockOrderStoneFinal.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockRainboquartzBlock.block).setRegistryName(BlockRainboquartzBlock.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockRainboquartzBlockChiseled.block).setRegistryName(BlockRainboquartzBlockChiseled.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockRainboquartzSlab.block, (BlockSlab) BlockRainboquartzSlab.block, (BlockSlab) BlockRainboquartzSlab.block_slab_double).setRegistryName(BlockRainboquartzSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockRainboquartzStair.block).setRegistryName(BlockRainboquartzStair.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockReditriteCobblestone.block).setRegistryName(BlockReditriteCobblestone.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianBuilderLab.block).setRegistryName(BlockSenterianBuilderLab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase1.block).setRegistryName(BlockSenterianCase1.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase2.block).setRegistryName(BlockSenterianCase2.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase3.block).setRegistryName(BlockSenterianCase3.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase4.block).setRegistryName(BlockSenterianCase4.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase5.block).setRegistryName(BlockSenterianCase5.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase6.block).setRegistryName(BlockSenterianCase6.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase7.block).setRegistryName(BlockSenterianCase7.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianCase8.block).setRegistryName(BlockSenterianCase8.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianLament.block).setRegistryName(BlockSenterianLament.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianLock.block).setRegistryName(BlockSenterianLock.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockSenterianSummonerSmall.block).setRegistryName(BlockSenterianSummonerSmall.block.getRegistryName()));
        event.getRegistry().register(BlockSenterianSummoner.item.setRegistryName(BlockSenterianSummoner.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockShalloiteBlock.block).setRegistryName(BlockShalloiteBlock.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockShalloiteBlockChiseled.block).setRegistryName(BlockShalloiteBlockChiseled.block.getRegistryName()));
        event.getRegistry().register(new ItemSlab(BlockShalloiteSlab.block, (BlockSlab) BlockShalloiteSlab.block, (BlockSlab) BlockShalloiteSlab.block_slab_double).setRegistryName(BlockShalloiteSlab.block.getRegistryName()));
        event.getRegistry().register(new ItemBlock(BlockShalloiteStair.block).setRegistryName(BlockShalloiteStair.block.getRegistryName()));
    }

    @SideOnly(Side.CLIENT)
    public static void registerModels(ModelRegistryEvent event) {
        BlockAbyssLiquid.registerModels(event);
        BlockAdeninite.registerModels(event);
        BlockAetherium.registerModels(event);
        BlockAwakenedDraconium.registerModels(event);
        BlockBalancedMatrix.registerModels(event);
        BlockBnightium.registerModels(event);
        BlockCanopium.registerModels(event);
        BlockChaoticDraconium.registerModels(event);
        BlockDensite.registerModels(event);
        BlockEverite.registerModels(event);
        BlockFireAlloy.registerModels(event);
        BlockFreezite.registerModels(event);
        BlockGenite.registerModels(event);
        BlockGuaninite.registerModels(event);
        BlockIceAlloy.registerModels(event);
        BlockLavarite.registerModels(event);
        BlockLumixeium.registerModels(event);
        BlockMistium.registerModels(event);
        BlockNaturaeum.registerModels(event);
        BlockNoxexeum.registerModels(event);
        BlockOceanium.registerModels(event);
        BlockOrderLiquid.registerModels(event);
        GctAllModels.block(BlockOrderCrystalOre.block);
        BlockFinalliumContainer.registerModels(event);
        BlockFinalliumContainerActive.registerModels(event);
        BlockPlasmarite.registerModels(event);
        BlockReditrite.registerModels(event);
        BlockSkyAlloy.registerModels(event);
        BlockSnowingium.registerModels(event);
        BlockThyminite.registerModels(event);
        BlockTonitruium.registerModels(event);
        GctAllModels.block(BlockWitheriumOreEnd.block);
        GctAllModels.block(BlockWitheriumOreNether.block);
        GctAllModels.block(BlockWitheriumOreOverworld.block);
        GctAllModels.block(BlockAlfCobbleStone.block);
        GctAllModels.block(BlockAlfDirt.block);
        GctAllModels.block(BlockAlfGrass.block);
        GctAllModels.block(BlockAlfSand.block);
        GctAllModels.block(BlockAlfStone.block);
        GctAllModels.block(BlockApocalypseAltar.block);
        GctAllModels.block(BlockApocalypseAltarBase.block);
        GctAllModels.block(BlockApocalypseBarrier.block);
        GctAllModels.block(BlockApocalypseBomb.block);
        GctAllModels.block(BlockArcaneVisReceiver.block);
        GctAllModels.block(BlockAstralPortalCore.block);
        GctAllModels.block(BlockAzathothiumOre.block);
        GctAllModels.block(BlockAzathothiumOreComplex.block);
        GctAllModels.block(BlockBesideVoidPortal1.block);
        GctAllModels.block(BlockBesideVoidPortal2.block);
        GctAllModels.block(BlockBesideVoidPortal3.block);
        GctAllModels.block(BlockBloodydirt.block);
        GctAllModels.block(BlockBloodygrass.block);
        GctAllModels.block(BlockBloodyrock.block);
        GctAllModels.block(BlockBlueFire.block);
        GctAllModels.block(BlockBotanicalStone.block);
        GctAllModels.block(BlockCorruptdirt.block);
        GctAllModels.block(BlockCorruptgrass.block);
        GctAllModels.block(BlockCorruptrock.block);
        GctAllModels.block(BlockCrystalsand.block);
        GctAllModels.block(BlockCrystalsandstone.block);
        GctAllModels.block(BlockCrystalsandstoneSlab.block);
        GctAllModels.block(BlockCrystalsandstoneStairs.block);
        GctAllModels.block(BlockCrystalsandstoneWalls.block);
        GctAllModels.block(BlockDenseDarkstone.block);
        GctAllModels.block(BlockDreadiumOre.block);
        GctAllModels.block(BlockDreamwoodLeaves.block);
        GctAllModels.block(BlockDreamwoodLog.block);
        GctAllModels.block(BlockDrurceLog.block);
        GctAllModels.block(BlockDrurcePlank.block);
        GctAllModels.block(BlockEarthboundAltar.block);
        GctAllModels.block(BlockEarthboundCore.block);
        GctAllModels.block(BlockEarthboundReceiver.block);
        GctAllModels.block(BlockElementiumOre.block);
        GctAllModels.block(BlockEthauxiumOre.block);
        GctAllModels.block(BlockEvileyeFence.block);
        GctAllModels.block(BlockEvileyeLeaves.block);
        GctAllModels.block(BlockEvileyeLog.block);
        GctAllModels.block(BlockEvileyePlank.block);
        GctAllModels.block(BlockEvileyeSlab.block);
        GctAllModels.block(BlockEvileyeStair.block);
        GctAllModels.block(BlockGravityDebris.block);
        GctAllModels.block(BlockHeavite.block);
        GctAllModels.block(BlockLivingwoodLeaves.block);
        GctAllModels.block(BlockLivingwoodLog.block);
        GctAllModels.block(BlockLunarGrass.block);
        GctAllModels.block(BlockLunarSoil.block);
        GctAllModels.block(BlockManaCobbleStone.block);
        GctAllModels.block(BlockManaDirt.block);
        GctAllModels.block(BlockManaFence.block);
        GctAllModels.block(BlockManaGrass.block);
        GctAllModels.block(BlockManaLeaves.block);
        GctAllModels.block(BlockManaLog.block);
        GctAllModels.block(BlockManaPlank.block);
        GctAllModels.block(BlockManaSlab.block);
        GctAllModels.block(BlockManaStairs.block);
        GctAllModels.block(BlockManaStone.block);
        GctAllModels.block(BlockManaStraw.block);
        GctAllModels.block(BlockManaStrawSmall.block);
        GctAllModels.block(BlockMeteor.block);
        GctAllModels.block(BlockNyarlathotepiumOre.block);
        GctAllModels.block(BlockNyralathotepiumOreComplex.block);
        GctAllModels.block(BlockOrichalcosDreamwood.block);
        GctAllModels.block(BlockOrichalcosOre.block);
        GctAllModels.block(BlockPolarisite.block);
        GctAllModels.block(BlockPolarisiteBrick.block);
        GctAllModels.block(BlockPolarisiteDark.block);
        GctAllModels.block(BlockPolarisiteDarkBrick.block);
        GctAllModels.block(BlockPolarisiteDarkSlab.block);
        GctAllModels.block(BlockPolarisiteDarkStair.block);
        GctAllModels.block(BlockPolarisiteDarkWall.block);
        GctAllModels.block(BlockPolarisiteSlab.block);
        GctAllModels.block(BlockPolarisiteStair.block);
        GctAllModels.block(BlockPolarisiteWall.block);
        GctAllModels.block(BlockPrimordialPortalHolder.block);
        GctAllModels.block(BlockPrimordialPortalHolder2.block);
        GctAllModels.block(BlockPrimordialStone.block);
        GctAllModels.block(BlockPrimordialStonebrick.block);
        GctAllModels.block(BlockPrimordialStonebrickSlab.block);
        GctAllModels.block(BlockPrimordialStonebrickStairs.block);
        GctAllModels.block(BlockPrimordialStonebrickWall.block);
        GctAllModels.block(BlockPrimordialStoneSlab.block);
        GctAllModels.block(BlockPrimordialStoneStairs.block);
        GctAllModels.block(BlockPrimordialStoneWall.block);
        GctAllModels.block(BlockPrimordialVisReceiver.block);
        GctAllModels.block(BlockReservedReserver.block);
        GctAllModels.block(BlockReserver.block);
        GctAllModels.block(BlockResonateDebris.block);
        GctAllModels.block(BlockResonateDebrisCracked.block);
        GctAllModels.block(BlockReversedAlfCobbleStone.block);
        GctAllModels.block(BlockReversedAlfDirt.block);
        GctAllModels.block(BlockReversedAlfGrass.block);
        GctAllModels.block(BlockReversedAlfStone.block);
        GctAllModels.block(BlockReversedDreamwoodFence.block);
        GctAllModels.block(BlockReversedDreamwoodLeaves.block);
        GctAllModels.block(BlockReversedDreamwoodLog.block);
        GctAllModels.block(BlockReversedDreamwoodPlank.block);
        GctAllModels.block(BlockReversedDreamwoodPlankRottened.block);
        GctAllModels.block(BlockReversedDreamwoodSlab.block);
        GctAllModels.block(BlockReversedDreamwoodStairs.block);
        GctAllModels.block(BlockRuinHolder.block);
        GctAllModels.block(BlockSaniteOre.block);
        GctAllModels.block(BlockSanityAltar.block);
        GctAllModels.block(BlockSeekAltar.block);
        GctAllModels.block(BlockSeekBrick.block);
        GctAllModels.block(BlockSeekFinder.block);
        GctAllModels.block(BlockShubniggurathiumOre.block);
        GctAllModels.block(BlockShubniggurathiumOreComplex.block);
        GctAllModels.block(BlockSolidPotEnergy.block);
        GctAllModels.block(BlockSolokFence.block);
        GctAllModels.block(BlockSolokLeaves.block);
        GctAllModels.block(BlockSolokLog.block);
        GctAllModels.block(BlockSolokPlank.block);
        GctAllModels.block(BlockSolokSlab.block);
        GctAllModels.block(BlockSolokStair.block);
        GctAllModels.block(BlockStarGrass.block);
        GctAllModels.block(BlockStarSoil.block);
        GctAllModels.block(BlockTerrasteelOre.block);
        GctAllModels.block(BlockVoidSeedContainer.block);
        GctAllModels.block(BlockWarprack.block);
        GctAllModels.block(BlockWarprackSlab.block);
        GctAllModels.block(BlockWarprackStair.block);
        GctAllModels.block(BlockWarprackWall.block);
        GctAllModels.block(BlockWildplainFence.block);
        GctAllModels.block(BlockWildplainLeaves.block);
        GctAllModels.block(BlockWildplainLog.block);
        GctAllModels.block(BlockWildplainPlank.block);
        GctAllModels.block(BlockWildplainSlab.block);
        GctAllModels.block(BlockWildplainStair.block);
        GctAllModels.block(BlockYogsothothiumOre.block);
        GctAllModels.block(BlockYogsothothiumOreComplex.block);
        GctAllModels.block(BlockDawniumOre.block);
        GctAllModels.block(BlockDeepslate.block);
        GctAllModels.block(BlockGlowstoneStair.block);
        GctAllModels.block(BlockOrderCobblestone.block);
        GctAllModels.block(BlockOrderCrystalBlock.block);
        GctAllModels.block(BlockOrderStone.block);
        GctAllModels.block(BlockOrderStoneBase.block);
        GctAllModels.block(BlockOrderStoneBrick.block);
        GctAllModels.block(BlockOrderStoneBrickChiseled.block);
        GctAllModels.block(BlockOrderStoneBrickCrashed.block);
        GctAllModels.block(BlockOrderStoneBrickCrashedSlab.block);
        GctAllModels.block(BlockOrderStoneBrickCrashedStair.block);
        GctAllModels.block(BlockOrderStoneBrickCrashedWall.block);
        GctAllModels.block(BlockOrderStoneBrickSlab.block);
        GctAllModels.block(BlockOrderStoneBrickStair.block);
        GctAllModels.block(BlockOrderStoneBrickWall.block);
        GctAllModels.block(BlockOrderStoneFinal.block);
        GctAllModels.block(BlockRainboquartzBlock.block);
        GctAllModels.block(BlockRainboquartzBlockChiseled.block);
        GctAllModels.block(BlockRainboquartzSlab.block);
        GctAllModels.block(BlockRainboquartzStair.block);
        GctAllModels.block(BlockReditriteCobblestone.block);
        GctAllModels.block(BlockSenterianBuilderLab.block);
        GctAllModels.block(BlockSenterianCase1.block);
        GctAllModels.block(BlockSenterianCase2.block);
        GctAllModels.block(BlockSenterianCase3.block);
        GctAllModels.block(BlockSenterianCase4.block);
        GctAllModels.block(BlockSenterianCase5.block);
        GctAllModels.block(BlockSenterianCase6.block);
        GctAllModels.block(BlockSenterianCase7.block);
        GctAllModels.block(BlockSenterianCase8.block);
        GctAllModels.block(BlockSenterianLament.block);
        GctAllModels.block(BlockSenterianLock.block);
        GctAllModels.block(BlockSenterianSummonerSmall.block);
        BlockSenterianSummoner.registerModels(event);
        GctAllModels.block(BlockShalloiteBlock.block);
        GctAllModels.block(BlockShalloiteBlockChiseled.block);
        GctAllModels.block(BlockShalloiteSlab.block);
        GctAllModels.block(BlockShalloiteStair.block);
    }

    private static void registerBlock(RegistryEvent.Register<Block> event, Block block, String registryName) {
        if (block.getRegistryName() == null) {
            block.setRegistryName(registryName);
        }
        event.getRegistry().register(block);
    }
}
